events {}

http {
    access_log /dev/stdout;
    error_log /dev/stderr notice;

    include /etc/nginx/conf.d/upstream.conf;

    server {
        listen 80;

        location = /health {
            default_type application/json;
            return 200 '{"status":"ok","service":"loadbalancer"}';
        }

        location / {
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_pass http://backend_pool;
        }
    }
}
